# Generated by Django 5.2.7 on 2025-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('ready', 'חבילה מוכנה'), ('custom', 'חבילה מותאמת')], help_text='ready = חבילה מוכנה מראש, custom = הרכבה אישית', max_length=20)),
                ('guests_count', models.IntegerField()),
                ('status', models.CharField(choices=[('new', 'חדש'), ('processing', 'בתהליך'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='new', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'הזמנה ',
                'verbose_name_plural': ' הזמנות',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text='מחיר המוצר בזמן ההזמנה', max_digits=10)),
                ('extra_price_per_person', models.DecimalField(decimal_places=2, default=0, help_text='תוספת מחיר אם זו מנה משודרגת', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'פריט בהזמנה',
                'verbose_name_plural': 'פריטים בהזמנות',
                'ordering': ['id'],
            },
        ),
    ]
