# Generated by Django 5.2.7 on 2025-11-12 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('packages', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, help_text='החבילה שנבחרה (NULL אם הרכבה אישית)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='packages.package'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package_category',
            field=models.ForeignKey(blank=True, help_text='הקטגוריה בחבילה (NULL אם הרכבה אישית)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='packages.packagecategory'),
        ),
    ]
